config/routes.rb
Reviewsomewebsites::Application.routes.draw do

  root :to => 'home#index'

  match 'sitesearch', :to => 'search#submit', :as => 'search'

  match '/newsites/', :to => 'newsites#index', :as => 'newsites'

  match '/sitemap-index.xml', :to => 'sitemap#index' , :as =>'sitemap_index'
  match '/sitemap-detail-(:page).xml', :to => 'sitemap#detail', :as => 'sitemap_detail'

  match ':controller(/:action(/:id(.:format)))'

  match '/:domain_name/', :to => 'sitedetails#index', :domain_name => /.*/, :as =>'sitedetails'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @websites = Website.recent :page => 1, :per_page => 5
  end
end

app/views/home/_website_list.erb
<div class="post">
	<div class="post-bgtop">
		<div class="post-bgbtm">
        <%= render :partial => "layouts/google_ad_horiz" %><br />
     </div>
   </div>
</div>


<% @websites.each do |website| %>

	<div class="post">
		<div class="post-bgtop">
			<div class="post-bgbtm">
          
				<h2 class="title"><%= link_to_site website %></h2>
				<p class="byline"> Added on <%= website.created_at.strftime "%m/%d/%y at %I:%M %p" %></p>
				<div class="entry">
					<p>
						<%= website.description %>
					</p>
				</div>
				<div class="meta">
					<p>
						<%= link_to "View More", sitedetails_path(  website.domain_name), :class => 'more' %>
					</p>
				</div>
			</div>
		</div>
	</div>

<% end %>

app/views/home/index.html.erb
<!-- Environment <%= RAILS_ENV %> -->
<%= render :partial => "website_list" %>




<div class="post">
	<div class="post-bgtop">
		<div class="post-bgbtm">
        <br />
          <span class="prev_page">&nbsp;</span>
          <%= link_to 'More >>>', newsites_path, :class => 'next_page' %>
  
     </div>
   </div>
</div>